### PR TITLE
Moved to Jersey Client 2.17

### PR DESCRIPTION
**Pull request by KMax**
I had a problem with the following exception:
```
com.sun.jersey.api.client.ClientHandlerException: com.sun.jersey.api.client.ClientHandlerException: A message body writer for Java type, class java.util.Collections$SingletonSet, and MIME media type, application/json, was not found
```
which I couldn't fix, so I decided to try to upgrade Jersey Client up to 2.17. And it helped! I tested the code locally with my OpenTSDB instance.

### CODE REVIEW

**Comment by gnomff** [comment]
Is there any chance this could be merged soonish? It would really help me out!

**Comment by KMax** [comment]
:+1:

**Comment by KMax** [comment]
@gnomff as a temporal solution I can suggest to you to use the version from my fork which contains the fix. To import it in your project you need to add the following to you `pom.xml`:

```
<dependency>
    <groupId>com.github.sps.metrics</groupId>
    <artifactId>metrics-opentsdb</artifactId>
    <version>1.0.5-SNAPSHOT</version>
</dependency>
```
and:
```
<repository>
    <id>metrics-opentsdb.mvn-repo</id>
    <url>https://raw.github.com/KMax/metrics-opentsdb/mvn-repo/</url>
    <snapshots>
        <enabled>true</enabled>
        <updatePolicy>always</updatePolicy>
    </snapshots>
</repository>
```

**Comment by gnomff** [comment]
Outstanding, thank you sir!

**Comment by sps** [comment]
Merged. Thank you for this @KMax!

**Pull request merged**
