### PR TITLE
Adding Tagged Metrics

### PR DESCRIPTION
**Pull request by rbuck23**

### CODE REVIEW

**Comment by shaikidris** [comment]
This is very handy to add tags dynamically to metrics. @rbuck23 any reason why is this not merged?
@rbuck23 I am assuming you are already using this in your production system. I would like to apply this patch and use it.
Thanks.

**Comment by shaikidris** [comment]
Adding patch to add taggedMetric, which allows us to add dynamic tags while publishing the metric.

**Comment by rbuck23** [comment]
@shaikidris I'm not sure why this hasn't been merged in.  Yes we use it in production at a very large corporation.

It almost feels as though this project is growing stale.  I have previously sent @sps an email and he said he'd look at it.  Maybe now with more interest he'll take another pass.

**Comment by rbuck23** [comment]
@shaikidris if this doesn't get merged in, you are welcome to work off my fork or clone your own (which it looks like you've done).

**Comment by sps** [comment]
@shaikidris @rbuck23 Sorry for the latency, this fell into a blindspot! 
This has been merged and released to maven central with version 1.0.7 

Thank you for your contributions!

**Comment by rbuck23** [comment]
Thanks, Sean!  I'd love to see this project eventually end up on this
<http://metrics.dropwizard.io/3.1.0/getting-started/> page and would like
to continue to contribute.

Randy

**Comment by sps** [comment]
I submitted [a PR](https://github.com/dropwizard/metrics/pull/993) back the metrics project to add links to this project.
I was so behind the 🎱 I missed there is/was also [interest](https://github.com/sps/metrics-opentsdb/issues/10) in integrating this into 4.x line of the main project.

**Pull request merged**
